version: "3.9"

services:

  db:
    image: postgres:15
    container_name: service_monitoring_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_monitoring_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: service_monitoring_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: